name: CMake Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v1
      with:
        cmake-version: '3.20'

    - name: Build with CMake and Make
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Check build status
      run: echo "Build successful" 
